version: "3.9"

services:
  broker:
    image: redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - data:/var/lib/docker/volumes/data/_data/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
    env_file:
      - stack.env

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.16.2.49,rw,nfsvers=4
      device: ":/mnt/purplehaze/data/docker-volumes/paperless-ngx/data"

  media:
  pgdata:
  redisdata:
